ALTER TABLE "BillingPlan"
ADD COLUMN "priceEditingAddonPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "shopPriceImageAddonPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Subscription"
ADD COLUMN "priceEditingAddonEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "priceEditingAddonPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "shopPriceImageAddonEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "shopPriceImageAddonPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "PlatformInvoice"
ADD COLUMN "priceEditingAddonFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "shopPriceImageAddonFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
